export const CHOOSED_TEAM_FORM_MEETING="CHOOSED_TEAM_FOR_MEETING"
export const SET_MEETING_DATE="SET_MEETING_DATE"
export const SET_MEETING_TIME="SET_MEETING_TIME"
export const SET_MEETING_SUBJECT="SET_MEETING_SUBJECT"